const IMAGES = {
    img_capa: new URL('./img_capa.png', import.meta.url).href,
    img_sobre: new URL('./formatura.jpg', import.meta.url).href,
    logo_pdv: new URL('./icon.png', import.meta.url).href,
    logo_siap: new URL('./image_2.png', import.meta.url).href,
    pdv_image0: new URL('./pdv/0.png', import.meta.url).href,
    pdv_image1: new URL('./pdv/1.png', import.meta.url).href,
    pdv_image2: new URL('./pdv/2.png', import.meta.url).href,
    pdv_image3: new URL('./pdv/3.png', import.meta.url).href,
    pdv_image4: new URL('./pdv/4.png', import.meta.url).href,
    siap_image1: new URL('./siap/1.png', import.meta.url).href,
    siap_image2: new URL('./siap/2.png', import.meta.url).href,
    siap_image3: new URL('./siap/3.png', import.meta.url).href,
    siap_image4: new URL('./siap/4.png', import.meta.url).href,
    hendeny_logo: new URL('./log.png', import.meta.url).href,
    hendeny_image1: new URL('./hendeny/0.png', import.meta.url).href,
    hendeny_image2: new URL('./hendeny/1.png', import.meta.url).href,
    hendeny_image3: new URL('./hendeny/2.png', import.meta.url).href,
    logo_onixx: new URL('./onixx/logo.png', import.meta.url).href,
    onixx_image1: new URL('./onixx/0.png', import.meta.url).href,
    onixx_image2: new URL('./onixx/1.png', import.meta.url).href,
    onixx_image3: new URL('./onixx/2.png', import.meta.url).href,
    logo_apollo: new URL('./apollo/logo.png', import.meta.url).href,
    apollo_image1: new URL('./apollo/0.png', import.meta.url).href,
    apollo_image2: new URL('./apollo/1.png', import.meta.url).href,
    apollo_image3: new URL('./apollo/2.png', import.meta.url).href,
    apollo_image4: new URL('./apollo/3.png', import.meta.url).href,
    apollo_image5: new URL('./apollo/4.png', import.meta.url).href,
    apollo_image6: new URL('./apollo/5.png', import.meta.url).href,

}

export default IMAGES